### PR TITLE
Allow for multiple source commands #2

### PR DESCRIPTION
**Pull request by andrey-starodubtsev**
seems like simple replacement of `command -v` with `which` does the trick

### CODE REVIEW

**Comment by bddenhartog** [comment]
Using `which` doesn't solve this issue, and is generally less preferred than `command -v` for testing existence of commands. You can see this by defining a function in a shell session, e.g. `testfunc() { echo "wahoo!" }`. Then, run `which testfunc` -- you can see that it outputs the function. You can confirm that this works the same for an installed program, e.g. `git`, by defining a function with the same name (which is what this repository does to accomplish the config injection).

Instead, a proper solution would be to look for the `git` executable in all possible locations, and set the value of `GIT_PROFILES_GIT_COMMAND` equal to one of those values (for example, on my local machine `/bin/git` would be the target. This would need to be tested on various machines, or really, looking at how git installs should suffice.

**Comment by andrey-starodubtsev** [comment]
Sorry for being leary, just tried it:

    $ cat <<EOL > 1.sh
    > testfunc() {
    > echo "testfunc"
    > }
    > EOL
    $ source 1.sh
    $ testfunc
    testfunc
    $ which testfunc
    $ echo $?
    1
    $ which git
    /usr/bin/git
    $ echo $?
    0
    $ uname -a
    Linux laptop 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    $ echo $BASH_VERSION
    4.3.46(1)-release

`man which` says:

       which returns the pathnames of the files (or links) which would be executed in the current environment, had its arguments been given as commands in a strictly POSIX-conformant shell.  It does
       this by searching the PATH for executable files matching the names of the arguments. It does not follow symbolic links.

Not a hint about shell functions. I decided not to re-implemented already available functionality.
Which shell/OS are you using?

**Comment by andrey-starodubtsev** [comment]
BTW, tried the same test on mac, with same results

**Comment by bddenhartog** [comment]
Odd results, Using `which` seems to work appropriately in `bash version 4.3.11(1)-release (x86_64-pc-linux-gnu)`, which is what the linux subsystem shell on Windows 10 (via build 1607; the Anniversary Update) uses. My primary machine, on which I wrote the earlier comment, uses `zsh` -- I don't know the specific version offhand, and am not at home anymore.

Regardless, `which`, while it seems to be a solution for bash users (at least with 4.3+), shouldn't really ever be used in shell scripting as it's not a builtin, like `command`. Relying on an external library means that you're opening yourself up to any number of potential issues. See the following SO discussions for reference:

- http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
- http://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then
- http://stackoverflow.com/questions/37056192/bash-which-vs-command-v

Again, I think the proper solution here is iterating through possible binary paths and checking for existence. Should be fairly simple, you could even use the directories in the user's `PATH` environment variable.

**Comment by andrey-starodubtsev** [comment]
Aha!
tried other shells, `which` is built-it command in both `zsh` and `tcsh`, but not in `bash` and `ksh` (at least in flavors I tried)! So, possible options are:
- use `/usr/bin/which`
- use `whence -p` on `zsh` (can't find similar parameter for tcsh's `which` builtin, but anyway, I'm afraid, `git-profiles` won't work in `tcsh` without serious modifications)
- parse `PATH` by ourselves
- combination of several approaches
Which way would you prefer?

**Comment by bddenhartog** [comment]
Note that existence of the library doesn't mean it is "built-in" -- the `which` executable probably comes with the distro itself, as you can see that `which` is not a builtin for ZSH and instead is aliased to `whence -c`.

Checking for the first `git` executable in `$PATH` would seem to make the most sense -- this would behave exactly like any shell's `PATH` parsing. We would want to make sure we do this once per session and make sure that it doesn't add too much load -- doing single-level checking for a `git` executable in each directory in `PATH` is, while not entirely comprehensive, probably good enough.

This avoids the whole `command/which/whence/etc` issue, but may cause undesired delay when sourcing the script. If that's the case, then detecting the shell and using the proper builtin would probably be the most efficient method.

**Comment by bddenhartog** [comment]
Looks good to me! I'll do some testing in various shells later on today and merge it in this evening.

**Pull request merged**
